{% set version = "3.0.1" %}
{% set sha256 = "a4c5745d1b06dfcb80b7704fe532eb765b44065a8fad9851e4258c8804140703" %}
{% set name = "sphinx_rtd_theme" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps -vv
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - sphinx >=6,<9
      run:
        - python >={{ python_min }}
        - sphinx >=6,<9
        - docutils >0.18,<0.22
        - sphinxcontrib-jquery >=4,<5

    test:
      requires:
        - python {{ python_min }}
      imports:
        - sphinx_rtd_theme

  - name: sphinx-rtd-theme
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - sphinx_rtd_theme

about:
  home: https://github.com/readthedocs/sphinx_rtd_theme/
  license: MIT
  license_file: LICENSE
  summary: ReadTheDocs.org theme for Sphinx, 2013 version.

  description: |
    This is a mobile-friendly sphinx theme made for readthedocs.org. It's currently in
    development there and includes some rtd variable checks that can be ignored if you're
    just trying to use it on your project outside of that site.
  dev_url: https://github.com/readthedocs/sphinx_rtd_theme/

extra:
  recipe-maintainers:
    - SylvainCorlay
