{% set version = "0.5.2" %}
{% set sha256 = "32bd3b5d13dc8186d7a42fc816a23d32e83a4827d7d9882948e7b837c232da5a" %}
{% set pkg_name = "sphinx_rtd_theme" %}		

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
    - sphinx >=1.6
  run:
    - python >=2.7
    - sphinx >=1.6
    - docutils <0.17

test:
  imports:
    - sphinx_rtd_theme

about:
  home: https://github.com/readthedocs/sphinx_rtd_theme/
  license: MIT
  license_file: LICENSE
  summary: ReadTheDocs.org theme for Sphinx, 2013 version.

  description: |
    This is a mobile-friendly sphinx theme made for readthedocs.org. It's currently in
    development there and includes some rtd variable checks that can be ignored if you're
    just trying to use it on your project outside of that site.
  dev_url: https://github.com/readthedocs/sphinx_rtd_theme/

extra:
  recipe-maintainers:
    - chohner
    - SylvainCorlay
