{% set version = "0.3.0" %}
{% set sha256 = "665135dfbdf8f1d218442458a18cf266444354b8c98eed93d1543f7e701cfdba" %}
{% set pkg_name = 'sphinx_rtd_theme' %}		

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sphinx_rtd_theme

about:
  home: https://github.com/rtfd/sphinx_rtd_theme
  license: Apache 2.0
  summary: 'Sphinx theme for readthedocs.org'

  description: |
    The sphinx_rtd_theme is a sphinx theme designed to look modern and be mobile-friendly.
    This theme is primary focused to be used on readthedocs.org but can work with your own
    sphinx projects. To read more and see a working demo head over to readthedocs.org.
  dev_url: https://github.com/rtfd/sphinx_rtd_theme

extra:
  recipe-maintainers:
    - chohner
    - SylvainCorlay
