travis:
  secure:
    BINSTAR_TOKEN: H3D9nehvd4UwIAnZzmsm4anTDIMJX26Bg0R7hz1PFyNIZRyI03LVWo8Z8MKCDYjJlSvxQR8LwdoTx6OfenZftgIociRmludwnL7wsJyLlzbD/h66jVz2TIBOvsXkG0zD6pGP4R66cdmuJ1avO4t6d+im6RxrsiTYu1lxzKeNBxYg0PemrqJ01Hk+T5p8TGi7v+UdUpj/xysSA28qPK//AnWPhVpoVlABfJB2FSRvJNPbV1jzZhZdemYMXmIfv6+KQTqEhRMLJe+p48uDmPhoKmDy0GvnJSaa3GCczo41MO54kx+ZtiPLlDK2O7g0SlzKBtw2zqKcVlro0hwgRVp2DY57Kp7i3rUJKaFZGmAJ+vxXndbkk4fCt1Nh091RbZIF0uysOzydifww8KOGy1xhedtDGpQ3gHUI5KEuPfW8W7x4X52hoyN0fMPd+sDi1Fw8H4QA4X9V+/Td9Ny8UTOeuYgQXd6Pwd8D4mPlCxYEmZyDiXod82Hd2sKbaEXDxr8aAc7U0PK2qP6Wyrw2mR9T85swAfmsScp9kWbLTEkAXwddgEW5BXrgqTUGJ3upAiR945WdhjTdWaHquL5oNJXlZ5pChp4S/wUgQNNP0bJpi9xRmauorqJMhdhgUPvpcfAG4a2LahPgrZl4fz5WHIB4obeYOsDPYB48LeKT921S1bM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
